# -*- coding: utf-8 -*-
"""ЛР7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12qS4yxaVL16eSzthKyBaQzq-oaLtYPlo
"""

data_al = [
    {'id': 1, 'pid': None, 'name': 'Каталог'},
    {'id': 2, 'pid': 1,    'name': 'Электроника'},
    {'id': 3, 'pid': 2,    'name': 'Телефоны'},
    {'id': 4, 'pid': 2,    'name': 'Ноутбуки'}
]

data_mp = [
    {'id': 1, 'path': '1',     'name': 'Каталог'},
    {'id': 2, 'path': '1.2',   'name': 'Электроника'},
    {'id': 3, 'path': '1.2.3', 'name': 'Телефоны'},
    {'id': 4, 'path': '1.2.4', 'name': 'Ноутбуки'}
]

def convert_to_mp(spisok):
    res = []
    for item in spisok:
        path = str(item['id'])
        curr = item
        while curr['pid'] is not None:
            for x in spisok:
                if x['id'] == curr['pid']:
                    curr = x
                    break
            path = str(curr['id']) + "." + path

        res.append({'id': item['id'], 'path': path, 'name': item['name']})
    return res


def convert_to_al(spisok):
    res = []
    for item in spisok:
        parts = item['path'].split('.')
        if len(parts) == 1:
            pid = None
        else:
            pid = int(parts[-2])

        res.append({'id': item['id'], 'pid': pid, 'name': item['name']})
    return res

print("ТЕСТ 1: AL -> MP")
res_mp = convert_to_mp(data_al)
for line in res_mp:
  print(line)

print("\nРезультат:", "Совпал" if res_mp == data_mp else "Ошибка")


print("\nТЕСТ 2: MP -> AL")
res_al = convert_to_al(data_mp)
for line in res_al:
  print(line)

print("\nРезультат:", "Совпал" if res_al == data_al else "Ошибка")